### ISSUE TITLE
loadFFTdata?

### ISSUE THREAD

**Issue by kristinksellers** [openmind-consortium/UCSF-rcs-data-analysis#5]
@roeegilron Is `loadFFTdata.m` in the rcsanalysis repo the most up-to-date script for loading FFT json files?

**Comment by roeegilron** [comment]
Yes, it is. I haven't worked on that function in a while so don't recall it's situation re bugs etc., and the `fftData` type is used rarely in most cases as if you stream this data type you mostly can't stream anything else (time domain, power etc.) but it is useful to plot after the fact in some cases.
